export const environment = {
  production: true,

  SOURCE_IMAGEM_ROOT: 'https://api.trisul-sa.com.br/cms/imagens/',

  API_ROOT: 'https://api.trisul-sa.com.br/cms/',

  //API_ROOT: 'http://localhost:5000/',

  API_PATH_DASHBOARD_CONTAGEM_CONVERSOES: 'dashboard/contagem-conversoes',
  AUTH_TOKEN_KEY: 'token',
  API_PATH_VALIDAR_TOKEN: 'validartoken/',
  API_PATH_LOGIN: 'login/',
  API_PATH_DASHBOARD: 'dashboard/',
  API_PATH_SEO: 'seo/',
  API_PATH_SEOPRODUTO: 'seoProduto/',
  API_PATH_PROMOCAO: 'promocao/',
  API_PATH_DIFERENCIAL: 'diferencial/',
  API_PATH_DIFERENCIALTIPO: 'diferencialTipo/',
  API_PATH_DIFERENCIALPRODUTO: 'diferencialProduto/',
  API_PATH_AREACOMUM: 'areacomum/',
  API_PATH_AREACOMUMTIPO: 'areacomumtipo/',
  API_PATH_AREACOMUMICONE: 'areacomumicone/',
  API_PATH_CENTRALVENDA: 'centralvenda/',
  API_PATH_APP_BANNERDESTAQUE: 'app/bannerdestaque/',
  API_PATH_APP_HOME_BAIRRODESTACADO: 'app/home/bairrodestacado/',
  API_PATH_APP_FILTRO_CIDADERECOMENDADA: 'app/filtro/cidaderecomendada/',
  API_PATH_APP_FILTRO_BAIRRORECOMENDADO: 'app/filtro/bairrorecomendado/',
  API_PATH_PROJETISTA: 'projetista/',
  API_PATH_CORRETOR: 'corretor/',
  API_PATH_PROJETISTATIPO: 'projetistaTipo/',
  API_PATH_ORDEM_PRODUTO: 'ordem/produto/',
  API_PATH_ENDERECO: 'endereco/',
  API_PATH_ENDERECO_ESTANDE: 'enderecoEstande/',
  API_PATH_PRODUTO: 'produto/',
  API_PATH_CARDHOME: 'cardhome/',
  API_PATH_PRODUTOPROMOCAO: 'produtopromocao/',
  API_PATH_PRODUTOSRELACIONADOS: 'produtosrelacionados/',
  API_PATH_GALERIA: 'galeria/',
  API_PATH_GALERIAPRODUTO: 'galeriaproduto/',
  API_PATH_GALERIATIPO: 'galeriatipo/',
  API_PATH_GALERIAIMAGEM: 'galeriaimagem/',
  API_PATH_IMAGEM: 'imagem/',
  API_PATH_CONJUNTO: 'conjunto/',
  API_PATH_PLANTA: 'planta/',
  API_PATH_PLANTATIPO: 'plantatipo/',
  API_PATH_STATUSVENDA: 'statusvenda/',
  API_PATH_STATUSCONJUNTO: 'statusconjunto/',
  API_PATH_STATUSOBRA: 'statusobra/',
  API_PATH_IMAGEMPRODUTO: 'imagemproduto/',
  API_PATH_COMODOTIPO: 'comodotipo/',
  API_PATH_HOTSITE: 'hotsite/',
  API_PATH_BAIRRO: 'bairro/',
  API_PATH_CIDADE: 'cidade/',
  API_PATH_ESTADO: 'estado/',
  API_PATH_PAIS: 'pais/',
  API_PATH_COMODO: 'comodo/',
  API_PATH_VANTAGEMCOMPRA: 'vantagemcompra/',
  API_PATH_OBRATIPO: 'obratipo/',
  API_PATH_PLANTACOMODO: 'plantacomodo/',
  API_PATH_CONJUNTOPLANTA: 'conjuntoplanta/',
  API_PATH_BOOKS: 'books/',
  API_PATH_EVOLUCAOOBRA: 'evolucaoobra/',
  API_PATH_REDIRECT: 'redirect/',
  API_PATH_CONFIGURACAOINTERFACEPRODUTO: 'configuracaointerfaceproduto/',
  API_PATH_PRODUTOVIDEO: 'produtovideo/',
  API_PATH_CRM: 'crm/',
  API_PATH_PRODUTO_CRM: 'produtocrm/'




};
